### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Alejandroq12** [Alejandroq12/group-capstone-js#21]
### In its description, paste a link to your GitHub project: 
- https://github.com/Alejandroq12/group-capstone-js/projects/1

### Add a note telling the reviewer how many people there are on your team:
- Hello, I hope you are having a great day.
- We are two teammates, the first one is @fpsapc [Student B] and the second one is @Alejandroq12 [Student A].
Have a good day.

**Comment by Olamarx** [comment]
> ### In its description, paste a link to your GitHub project:
> * https://github.com/Alejandroq12/group-capstone-js
> 
> ### Add a note telling the reviewer how many people there are on your team:
> * Hello, I hope you are having a great day.
> * We are two teammates, the first one is @fpsapc [Student B] and the second one is @Alejandroq12 [Student A].
>   Have a good day.

Hi @Alejandroq12, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a link to your Kanban board project. Please note, the link is not to your repo but to your Kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Alejandroq12** [comment]
Thank you very much for your feedback. I already fixed it and I will submit another review. Thanks.
